### ISSUE TITLE
The version 0.5.0 build seems to have failed? It is also not available via pip install

### ISSUE THREAD

**Issue by MilanMIBM** [IBM/watsonxdata-python-sdk#3]
Hi, it seems like the 0.5.0 version build has failed, it is also not available via pip even though the github page states that it is the latest release.

<img width="1145" alt="Image" src="https://github.com/user-attachments/assets/eff7f45c-5713-4f07-a2d1-fa8b28381c07" />

**Comment by LeifLundbergIBM** [comment]
@fanfeigithub @emilyz-github @yashgogoriya @Ann-Mary-Luke @Raufk

Hello,

The build keeps failing and not being published to PyPi.org.

![Image](https://github.com/user-attachments/assets/26f077a8-1ef9-4f43-8516-7c64e3ac6bf4)


The file `.travis.yml` needs to be updated. Haven't tested it but this or something similar should work.

```
- provider: pypi
  username: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
    python: '3.8'
    tags: true
    branch: 
      - main
      - master
      - /^v\d+\.\d+\.\d+$/  
 ```
